### ISSUE TITLE
Unsure how to deploy

### ISSUE THREAD

**Issue by jorgeavaldez** [NEAR-labs/contracts.near-linkdrop#4]
One thing I noticed is that the tests rely on an external linkdrop contract, the wasm for which exists in this repo. When deploying to test net, is there an existing account creator? Should I be setting EXTERNAL_LINKDROP_ACCOUNT to linkdrop.testnet?

**Comment by jorgeavaldez** [comment]
Figured it out

I had no idea you could manually invoke create_account on testnet.

And the included external_linkdrop.wasm seems to proxy this behavior.

**Comment by eclipseeer** [comment]
@jorgeavaldez no, you don't even need to deploy a 'linkdrop' contract - you can use an existing one - [linkdrop.testnet](https://explorer.testnet.near.org/accounts/linkdrop.testnet). `external_linkdrop.wasm` - this is the [original linkdrop](https://github.com/near/near-linkdrop)

But notice that contracts are not ready yet, and will be changed in the future.
